# Generated by Django 4.1 on 2023-01-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
