# Generated by Django 4.1 on 2023-01-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
