# Generated by Django 4.1 on 2023-01-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
